{
    "Computer":  "FRWSTH",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1758554976642)\/",
                       "Source":  "Microsoft-Windows-Perflib",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Windows cannot load the extensible counter DLL \"C:\\WINDOWS\\system32\\sysmain.dll\" (Win32 error code The specified module could not be found.).",
                       "Id":  1023,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  18901
                   },
                   {
                       "TimeCreated":  "\/Date(1758554853656)\/",
                       "Source":  "NETLOGON",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "This computer was not able to set up a secure session with a domain controller in domain KHOETECH due to the following: \r",
                       "Id":  5719,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6998
                   },
                   {
                       "TimeCreated":  "\/Date(1758554432901)\/",
                       "Source":  "Microsoft-Windows-GroupPolicy",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The processing of Group Policy failed because of lack of network connectivity to a domain controller. This may be a transient condition. A success message would be generated once the machine gets connected to the domain controller and Group Policy has successfully processed. If you do not see a success message for several hours, then contact your administrator.",
                       "Id":  1129,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6993
                   },
                   {
                       "TimeCreated":  "\/Date(1758554419337)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to load task \"\\Microsoft\\Windows\\UpdateOrchestrator\\StartOobeAppsScanAfterUpdate\" at service startup. Additional Data: Error Value: 2147942402.",
                       "Id":  146,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  138327
                   },
                   {
                       "TimeCreated":  "\/Date(1758554419337)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task instantiation failed \"\\Microsoft\\Windows\\UpdateOrchestrator\\StartOobeAppsScanAfterUpdate\". Check point: Ubpm-RegisterConsumer. Error Value: 2147942402.",
                       "Id":  151,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  138326
                   },
                   {
                       "TimeCreated":  "\/Date(1758554411617)\/",
                       "Source":  "iaStorAC",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "Error log: Smart event occured on disk :49QA14SYK00N  ",
                       "Id":  4102,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6901
                   },
                   {
                       "TimeCreated":  "\/Date(1758554352131)\/",
                       "Source":  "Microsoft-Windows-Eventlog",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The event logging service encountered an error (5) while enabling publisher {8e889f0c-7d54-52b3-e4ae-2c8b27a482c2} to channel Microsoft-Windows-LocationServiceProvider/Operational. This does not affect channel operation, but does affect the ability of the publisher to raise events to the channel. One common reason for this error is that the Provider is using ETW Provider Security and has not granted enable permissions to the Event Log service identity.",
                       "Id":  30,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6843
                   },
                   {
                       "TimeCreated":  "\/Date(1758554327407)\/",
                       "Source":  "Microsoft-Windows-CAPI2",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Cryptographic Services failed while processing the OnIdentity() call in the System Writer Object.",
                       "Id":  513,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  18789
                   },
                   {
                       "TimeCreated":  "\/Date(1758554288695)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The EventLog service terminated with the following error: \r",
                       "Id":  7023,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6707
                   },
                   {
                       "TimeCreated":  "\/Date(1758554288373)\/",
                       "Source":  "EventLog",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The previous system shutdown at 8:05:10 AM on ‎9/‎22/‎2025 was unexpected.",
                       "Id":  6008,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  6601
                   }
               ],
    "LastPoll":  "09/22 08:38"
}