{
    "Computer":  "SERVER2019",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1760625813041)\/",
                       "Source":  "LHWinService",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "  There may be a configuration problem: please check the logs.",
                       "Id":  100,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  261741
                   },
                   {
                       "TimeCreated":  "\/Date(1760602776765)\/",
                       "Source":  "Microsoft-Windows-WindowsUpdateClient",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "Installation Failure: Windows failed to install the following update with error 0x80073701: 2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428).",
                       "Id":  20,
                       "ErrorCode":  "0x80073701",
                       "UpdateTitle":  "2025-09 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5065428)",
                       "EventRecordID":  2928366
                   },
                   {
                       "TimeCreated":  "\/Date(1760587248209)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Offsite Online Backup Service service failed to start due to the following error: \r",
                       "Id":  7000,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2927759
                   },
                   {
                       "TimeCreated":  "\/Date(1760575049849)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "A timeout was reached (30000 milliseconds) while waiting for the VyneSync.Service service to connect.",
                       "Id":  7009,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2927216
                   },
                   {
                       "TimeCreated":  "\/Date(1760574881130)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Sentinel Agent service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 20000 milliseconds: Restart the service.",
                       "Id":  7031,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2926970
                   },
                   {
                       "TimeCreated":  "\/Date(1760574875640)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The DentrixACEServer service did not shut down properly after receiving a preshutdown control.",
                       "Id":  7043,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2926967
                   },
                   {
                       "TimeCreated":  "\/Date(1760574871683)\/",
                       "Source":  "Microsoft-Windows-DistributedCOM",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "DCOM got error \"1115\" attempting to start the service BITS with arguments \"Unavailable\" in order to run the server:\r",
                       "Id":  10005,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2926964
                   },
                   {
                       "TimeCreated":  "\/Date(1760574845258)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Update Orchestrator Service service terminated with the following error: \r",
                       "Id":  7023,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  2926954
                   }
               ],
    "LastPoll":  "10/16 08:06"
}