{
    "Computer":  "VSPS1",
    "Events":  [
                   {
                       "TimeCreated":  "\/Date(1760719964229)\/",
                       "Source":  "Microsoft-Windows-WindowsUpdateClient",
                       "LogName":  "Microsoft-Windows-WindowsUpdateClient/Operational",
                       "Level":  "Error",
                       "Message":  "Windows Update failed to check for updates with error 0x80244022.",
                       "Id":  25,
                       "ErrorCode":  "0x80244022",
                       "UpdateTitle":  null,
                       "EventRecordID":  31019
                   },
                   {
                       "TimeCreated":  "\/Date(1760701990613)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to start instance \"{54a83e4d-3f67-48fd-a25a-b054e86be504}\" of \"\\Microsoft\\Windows\\.NET Framework\\.NET Framework NGEN v4.0.30319\"  task for user \"NT AUTHORITY\\SYSTEM\" . Additional Data: Error Value: 2147946720.",
                       "Id":  103,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  173262
                   },
                   {
                       "TimeCreated":  "\/Date(1760701990613)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to complete task \"\\Microsoft\\Windows\\.NET Framework\\.NET Framework NGEN v4.0.30319\" , instance \"{54a83e4d-3f67-48fd-a25a-b054e86be504}\" , action \"\" . Additional Data: Error Value: 2147946720.",
                       "Id":  202,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  173261
                   },
                   {
                       "TimeCreated":  "\/Date(1760700460486)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to start \"\\Microsoft\\Windows\\Workplace Join\\Automatic-Device-Join\" task for user \"(default user)\". Additional Data: Error Value: 2147943568.",
                       "Id":  101,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  173116
                   },
                   {
                       "TimeCreated":  "\/Date(1760700388330)\/",
                       "Source":  "Microsoft-Windows-Perflib",
                       "LogName":  "Application",
                       "Level":  "Error",
                       "Message":  "Access to performance data was denied to user \"SYSTEM\" (value from GetUserName() for the running thread) as attempted from module \"C:\\Program Files\\SentinelOne\\Sentinel Agent 24.2.3.471\\SentinelAgent.exe\" (value from GetModuleFileName() for the binary that issued the query).",
                       "Id":  1000,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  30991
                   },
                   {
                       "TimeCreated":  "\/Date(1760700380417)\/",
                       "Source":  "Service Control Manager",
                       "LogName":  "System",
                       "Level":  "Error",
                       "Message":  "The Sentinel Agent service did not shut down properly after receiving a preshutdown control.",
                       "Id":  7043,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  218094
                   },
                   {
                       "TimeCreated":  "\/Date(1760700168194)\/",
                       "Source":  "Microsoft-Windows-TaskScheduler",
                       "LogName":  "Microsoft-Windows-TaskScheduler/Operational",
                       "Level":  "Error",
                       "Message":  "Task Scheduler failed to launch action \"%windir%\\system32\\devicecensus.exe\" in instance \"{cddd1157-065b-4e05-8b2b-4a817589deb5}\" of task \"\\Microsoft\\Windows\\Device Information\\Device\". Additional Data: Error Value: 2147943515.",
                       "Id":  203,
                       "ErrorCode":  {

                                     },
                       "UpdateTitle":  null,
                       "EventRecordID":  173097
                   }
               ],
    "LastPoll":  "10/17 22:07"
}